---
title: "NodeVerse Simulations"
author: "Francesco Cecere"
date: "`r Sys.Date()`"
format: 
  html:
    code-fold: true
    toc: true
    toc-depth: 2
    toc-location: left
    number-sections: true
    theme: superhero
editor: visual
---

## Load Libraries and data

```{r}
library(tidyverse)
library(GENIE3)
library(igraph)
library(ggraph)
library(pROC)
library(RColorBrewer)
library(scales)
library(gridExtra)
library(INetTool)
library(learn2count)
library(reticulate)

use_python("/usr/bin/python3", required = TRUE)
arboreto <- import("arboreto.algo")
pandas <- import("pandas")
numpy <- import("numpy")

source("./../R/earlyj.R")
source("./../R/infer_networks.R")
source("./../R/generate_adjacency.R")
source("./../R/symmetrize.R")
source("./../R/plotROC.R")
source("./../R/cutoff_adjacency.R")
source("./../R/pscores.R")
source("./../R/plotg.R")
source("./../R/create_consensus.R")
source("./../R/compare_consensus.R")

time <- list()

ddir <- "/home/francescoc/Desktop/GRN_project/analysis/GENIE3/data"
pdir <- "/home/francescoc/Desktop/GRN_project/analysis/GENIE3/plots"

adjm <- as.matrix(read.table("./../analysis/adjm_p677.txt"))
count_matrices <- readRDS("./../analysis/sim_n500p677.RDS")
dim(count_matrices[[1]])


```

##  GENIE3 

### Late integration

```{r}
set.seed(1234)
time[["GENIE3_late_15Cores"]] <- system.time(
  genie3_late <- infer_networks(count_matrices, 
                                method="GENIE3",
                                nCores = 15)
)

saveRDS(genie3_late, paste(ddir, "genie3_late_simp677.RDS", sep = "/"))
```

#### Symmetrize and ROC

```{r}
genie3_late_wadj <- generate_adjacency(genie3_late, ground.truth = adjm)
sgenie3_late_wadj <- symmetrize(genie3_late_wadj, weight_function = "mean")

png(paste(pdir, "genie3_late_simp677_auc.png", sep = "/"), width = 2400, height = 1800, res = 300)
genie3_late_auc <- plotROC(sgenie3_late_wadj, adjm, plot_title = "ROC curve - GENIE3 Late Integration")
dev.off()
```

#### Cutoff

```{r}
sgenie3_late_adj <- cutoff_adjacency(count_matrices = count_matrices,
                                     weighted_adjm_list = sgenie3_late_wadj, 
                                     ground.truth = adjm,
                                     n = 3,
                                     method = "GENIE3",
                                     nCores = 15)

png(paste(pdir, "genie3_late_simp677_scores.png", sep = "/"), width = 2400, height = 1800, res = 300)
scores.genie3.late.all <- pscores(adjm, sgenie3_late_adj)
dev.off()

png(paste(pdir, "genie3_late_simp677_mplots.png", sep = "/"), width = 2400, height = 2400, res = 300)
plots <- plotg(sgenie3_late_adj)
dev.off()

cbind(scores.genie3.late.all$Statistics, genie3_late_auc) %>% write.table(., paste(ddir, "genie3_late_simp677_perf.txt", sep = "/"), sep = "\t", quote = F, col.names = T, row.names = F)
```

#### Consensus

```{r}
consesusm <- create_consensus(sgenie3_late_adj, method="vote")
consesusu <- create_consensus(sgenie3_late_adj, method="union")
consesunet <- create_consensus(adj_matrix_list = sgenie3_late_adj, weighted_list = sgenie3_late_wadj, method = "INet", threshold = 0.05, ncores = 15)

png(paste(pdir, "genie3_late_simp677_vote_score.png", sep = "/"), width = 2400, height = 2400, res = 300)
scores.genie3.late <- pscores(adjm, list(consesusm))
dev.off()
png(paste(pdir, "genie3_late_simp677_union_score.png", sep = "/"), width = 2400, height = 2400, res = 300)
scoresu.genie3.late <- pscores(adjm, list(consesusu))
dev.off()
png(paste(pdir, "genie3_late_simp677_inet_score.png", sep = "/"), width = 2400, height = 2400, res = 300)
scoresnet.genie3.late <- pscores(adjm, list(consesunet))
dev.off()
```

#### Plot comparison 

```{r}
png(paste(pdir, "genie3_late_simp677_vote_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(consesusm, adjm)
dev.off()
png(paste(pdir, "genie3_late_simp677_union_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(consesusu, adjm)
dev.off()
png(paste(pdir, "genie3_late_simp677_inet_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(consesunet, adjm)
dev.off()
```

### Early integration

```{r}
early_matrix <- list(earlyj(count_matrices))

set.seed(1234)
time[["GENIE3_early_15Cores"]] <- system.time(
  genie3_early <- infer_networks(early_matrix, method="GENIE3", nCores = 15)
)

saveRDS(genie3_early, paste(ddir, "genie3_early_simp677.RDS", sep = "/"))
```

#### Symmetrize and ROC

```{r}
genie3_early_wadj <- generate_adjacency(genie3_early, ground.truth = adjm)
sgenie3_early_wadj <- symmetrize(genie3_early_wadj, weight_function = "mean")

png(paste(pdir, "genie3_early_simp677_auc.png", sep = "/"), width = 2400, height = 1800, res = 300)
genie3_early_auc <- plotROC(sgenie3_early_wadj, adjm, plot_title = "ROC curve - GENIE3 Early Integration")
dev.off()
```

#### Cutoff

```{r}
sgenie3_early_adj <- cutoff_adjacency(count_matrices = early_matrix,
                                      weighted_adjm_list = sgenie3_early_wadj, 
                                      ground.truth = adjm,
                                      n = 2,
                                      method = "GENIE3",
                                      nCores = 15)

png(paste(pdir, "genie3_early_simp677_scores.png", sep = "/"), width = 2400, height = 1800, res = 300)
scores.genie3.early <- pscores(adjm, sgenie3_early_adj)
dev.off()

png(paste(pdir, "genie3_early_simp677_mplots.png", sep = "/"), width = 2400, height = 2400, res = 300)
plots <- plotg(sgenie3_early_adj)
dev.off()

cbind(scores.genie3.early$Statistics, genie3_early_auc) %>% write.table(., paste(ddir, "genie3_early_simp677_perf.txt", sep = "/"), sep = "\t", quote = F, col.names = T, row.names = F)
```

#### Plot comparison

```{r}
png(paste(pdir, "genie3_early_simp677_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(sgenie3_early_adj[[1]], adjm)
dev.off()
```

## GRNBoost2

### Late integration

```{r}
set.seed(1234)
time[["grnboost_late"]] <- system.time(
  grnboost_late <- infer_networks(count_matrices, 
                                method="GRNBoost2",
                                nCores = 15)
)

saveRDS(grnboost_late, paste(ddir, "grnboost_late_simp677.RDS", sep = "/"))
```

#### Symmetrize and ROC

```{r}
grnboost_late_wadj <- generate_adjacency(grnboost_late, ground.truth = adjm)
sgrnboost_late_wadj <- symmetrize(grnboost_late_wadj, weight_function = "mean")

png(paste(pdir, "grnboost_late_simp677_auc.png", sep = "/"), width = 2400, height = 1800, res = 300)
grnboost_late_auc <- plotROC(sgrnboost_late_wadj, adjm, plot_title = "ROC curve - grnboost Late Integration")
dev.off()
```

#### Cutoff

```{r}
sgrnboost_late_adj <- cutoff_adjacency(count_matrices = count_matrices,
                                     weighted_adjm_list = sgrnboost_late_wadj, 
                                     ground.truth = adjm,
                                     n = 3,
                                     method = "GRNBoost2",
                                     nCores = 15)

png(paste(pdir, "grnboost_late_simp677_scores.png", sep = "/"), width = 2400, height = 1800, res = 300)
scores.grnboost.late.all <- pscores(adjm, sgrnboost_late_adj)
dev.off()

png(paste(pdir, "grnboost_late_simp677_mplots.png", sep = "/"), width = 2400, height = 2400, res = 300)
plots <- plotg(sgrnboost_late_adj)
dev.off()

cbind(scores.grnboost.late.all$Statistics, grnboost_late_auc) %>% write.table(., paste(ddir, "grnboost_late_simp677_perf.txt", sep = "/"), sep = "\t", quote = F, col.names = T, row.names = F)
```

#### Consensus

```{r}
consesusm <- create_consensus(sgrnboost_late_adj, method="vote")
consesusu <- create_consensus(sgrnboost_late_adj, method="union")
consesunet <- create_consensus(adj_matrix_list = sgrnboost_late_adj, weighted_list = sgrnboost_late_wadj, method = "INet", threshold = 0.05)

png(paste(pdir, "grnboost_late_simp677_vote_score.png", sep = "/"), width = 2400, height = 2400, res = 300)
scores.grnboost.late <- pscores(adjm, list(consesusm))
dev.off()
png(paste(pdir, "grnboost_late_simp677_union_score.png", sep = "/"), width = 2400, height = 2400, res = 300)
scoresu.grnboost.late <- pscores(adjm, list(consesusu))
dev.off()
png(paste(pdir, "grnboost_late_simp677_inet_score.png", sep = "/"), width = 2400, height = 2400, res = 300)
scoresnet.grnboost.late <- pscores(adjm, list(consesunet))
dev.off()

```

#### Plot comparison 

```{r}
png(paste(pdir, "grnboost_late_simp677_vote_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(consesusm, adjm)
dev.off()
png(paste(pdir, "grnboost_late_simp677_union_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(consesusu, adjm)
dev.off()
png(paste(pdir, "grnboost_late_simp677_inet_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(consesunet, adjm)
dev.off()

```

### Early integration 

```{r}
early_matrix <- list(earlyj(count_matrices))

set.seed(1234)
time[["grnboost_early"]] <- system.time(
  grnboost_early <- infer_networks(early_matrix, method="GRNBoost2")
)

saveRDS(grnboost_early, paste(ddir, "grnboost_early_simp677.RDS", sep = "/"))
```

#### Symmetrize and ROC

```{r}
grnboost_early_wadj <- generate_adjacency(grnboost_early, ground.truth = adjm)
sgrnboost_early_wadj <- symmetrize(grnboost_early_wadj, weight_function = "mean")

png(paste(pdir, "grnboost_early_simp677_auc.png", sep = "/"), width = 2400, height = 1800, res = 300)
grnboost_early_auc <- plotROC(sgrnboost_early_wadj, adjm, plot_title = "ROC curve - grnboost Early Integration")
dev.off()
```

#### Cutoff

```{r}
sgrnboost_early_adj <- cutoff_adjacency(count_matrices = early_matrix,
                                      weighted_adjm_list = sgrnboost_early_wadj, 
                                      ground.truth = adjm,
                                      n = 2,
                                      method = "GRNBoost2",
                                      nCores = 15)

png(paste(pdir, "grnboost_early_simp677_scores.png", sep = "/"), width = 2400, height = 1800, res = 300)
scores.grnboost.early <- pscores(adjm, sgrnboost_early_adj)
dev.off()

png(paste(pdir, "grnboost_early_simp677_mplots.png", sep = "/"), width = 2400, height = 2400, res = 300)
plots <- plotg(sgrnboost_early_adj)
dev.off()

cbind(scores.grnboost.early$Statistics, grnboost_early_auc) %>% write.table(., paste(ddir, "grnboost_early_simp677_perf.txt", sep = "/"), sep = "\t", quote = F, col.names = T, row.names = F)
```

#### Plot comparison 

```{r}
png(paste(pdir, "grnboost_early_simp677_plot.png", sep = "/"), width = 4000, height = 2400, res = 300)
ajm_compared <- compare_consensus(sgrnboost_early_adj[[1]], adjm)
dev.off()
```

