---
title: "scGraphVerse PBMC Data and Ground Truth"
author: "Francesco Cecere"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: cerulean
    df_print: paged
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r}
knitr::opts_knit$set(root.dir = "/home/francescoc/Desktop/scGraphVerse/data", 
  warning = FALSE, 
  message = FALSE, 
  error = FALSE)
```

## Load Libraries

```{r load-libraries}

library(biomaRt)
library(DT)
library(tidyverse)
library(Seurat)
library(STRINGdb)

library(scGraphVerse)
```

## Load Atlas Data

```{r Download Seurat Object}
options(timeout = 600)

# PBMC Dataset: Local and systemic responses to SARS-CoV-2 infection in children and adults
seurat_url <- "https://datasets.cellxgene.cziscience.com/89619149-162f-4839-8e97-24735924417c.rds"

seurat_object <- download_Atlas(seurat_url)

seurat_subset <- subset(
  x = seurat_object,
  subset = disease == "normal" & cell_type == "CD4-positive helper T cell" & donor_id %in% c("AN6", "AN9", "NP18")
)

```

```{r Filter Seurat object}
meta_features <- seurat_subset[["RNA"]]@meta.features
stopifnot(all(rownames(meta_features) == rownames(seurat_subset[["RNA"]]@data)))

new_rownames <- meta_features$name
new_rownames <- seurat_subset@assays$RNA@meta.features$name

if (length(new_rownames) != nrow(seurat_subset[["RNA"]]@data)) {
  stop("The length of new_rownames does not match the number of features.")
}

assay <- seurat_subset[["RNA"]] # Access the RNA assay
rownames(assay@counts) <- new_rownames
rownames(assay@data) <- new_rownames
rownames(assay@meta.features) <- new_rownames

seurat_subset[["RNA"]] <- assay

```

## Filtering step

```{r, fig.width=5, fig.height=7}
seurat_subset <- PercentageFeatureSet(seurat_subset, "^MT-", col.name = "percent_mito")
# Ribosomal
seurat_subset <- PercentageFeatureSet(seurat_subset, "^RP[SL]", col.name = "percent_ribo")

feats <- c("nFeature_RNA", "nCount_RNA", "percent_mito", "percent_ribo")
VlnPlot(seurat_subset, group.by = "donor_id", split.by = "donor_id", features = feats, pt.size = 0.1, ncol = 2)
```

```{r}
FeatureScatter(seurat_subset, "nCount_RNA", "nFeature_RNA", group.by = "donor_id", pt.size = .5)
```

```{r, fig.width=5, fig.height=7}
selected_c <- WhichCells(seurat_subset, expression = nFeature_RNA > 200)
selected_f <- rownames(seurat_subset)[Matrix::rowSums(seurat_subset) > 3]

seurat_subset_filt <- subset(seurat_subset, features = selected_f, cells = selected_c)
dim(seurat_subset_filt)
table(seurat_subset_filt$donor_id)

C <- seurat_subset_filt@assays$RNA@counts
C@x <- C@x / rep.int(colSums(C), diff(C@p)) * 100
most_expressed <- order(Matrix::rowSums(C), decreasing = T)[20:1]
boxplot(as.matrix(t(C[most_expressed, ])),
    cex = 0.1, las = 1, xlab = "Percent counts per cell",
    col = (scales::hue_pal())(20)[20:1], horizontal = TRUE
)
```

```{r, fig.width=7, fig.height=7}
selected_mito <- WhichCells(seurat_subset_filt, expression = percent_mito < 20)
selected_ribo <- WhichCells(seurat_subset_filt, expression = percent_ribo > 5)

# and subset the object to only keep those cells
seurat_subset_filt <- subset(seurat_subset_filt, cells = selected_mito)
seurat_subset_filt <- subset(seurat_subset_filt, cells = selected_ribo)
dim(seurat_subset_filt)

feats <- c("nFeature_RNA", "nCount_RNA", "percent_mito", "percent_ribo")
VlnPlot(seurat_subset_filt, group.by = "donor_id", features = feats, pt.size = 0.1, ncol = 2) + NoLegend()

```

```{r, fig.width=5, fig.height=7}
# Filter MALAT1
seurat_subset_filt <- seurat_subset_filt[!grepl("MALAT1", rownames(seurat_subset_filt)), ]

# Filter Mitocondrial
seurat_subset_filt <- seurat_subset_filt[!grepl("^MT-", rownames(seurat_subset_filt)), ]

# Filter Ribossomal gene (optional if that is a problem on your data)
seurat_subset_filt <- seurat_subset_filt[ ! grepl("^RP[SL]", rownames(seurat_subset_filt)), ]

dim(seurat_subset_filt)
C <- seurat_subset_filt@assays$RNA@counts
C@x <- C@x / rep.int(colSums(C), diff(C@p)) * 100
most_expressed <- order(Matrix::rowSums(C), decreasing = T)[20:1]
boxplot(as.matrix(t(C[most_expressed, ])),
    cex = 0.1, las = 1, xlab = "Percent counts per cell",
    col = (scales::hue_pal())(20)[20:1], horizontal = TRUE
)
```

## Adjacency matrix top1200

```{r Generate Adjacency matrice}
pathgenes <- selgene(seurat_object = seurat_subset_filt, cell_type = "CD4-positive helper T cell", top_n = 1200)

options(timeout = 2000)
result <- stringdb_adjacency(
  genes          = pathgenes,
  species        = 9606,
  required_score = 900,
  keep_all_genes = F
)

wadjm <- result$weighted
adjm <- result$binary

common_names <- intersect(rownames(adjm), colnames(adjm))
adjm <- adjm[common_names, common_names, drop = FALSE]

sorted_names <- sort(rownames(adjm))
adjm <- adjm[sorted_names, sorted_names]

print(dim(wadjm))
print(dim(adjm))

write.table(adjm, "./../analysis/simulation/adjacency/adjm_top1200_p500.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)
write.table(wadjm, "./../analysis/simulation/adjacency/wadjm_top1200_p500.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)

wadjm %>%
    datatable(extensions = 'Buttons',
            options = list(
              dom = 'Bfrtip',
              buttons = c('csv', 'excel'),
              scrollX = TRUE,
              pageLength = 10), 
            caption = "STRING Adjacency Top1000 genes")

adjm %>%
    datatable(extensions = 'Buttons',
            options = list(
              dom = 'Bfrtip',
              buttons = c('csv', 'excel'),
              scrollX = TRUE,
              pageLength = 10), 
            caption = "STRING Adjacency Top1000 genes")

```

## Split data for donor_id

```{r format control Seurat data}
genes_to_keep <- intersect(pathgenes, rownames(seurat_subset_filt))
seurat_subset_filt_case <- subset(seurat_subset_filt, features = genes_to_keep)
seurat_subset_filt_case@assays$RNA@counts <- as.matrix(seurat_subset_filt_case@assays$RNA@counts)

saveRDS(seurat_subset_filt_case, "./../analysis/casestudy/PBMC.top1200.RDS")

ncells_case <- as.matrix(seurat_subset_filt_case@assays$RNA@counts)
ncells_case <- ncells_case[rownames(adjm),]

mean(colSums(ncells_case))
```

## Create Ground Truth Network

```{r plot Ground truth}
gtruth <- igraph::graph_from_adjacency_matrix(adjm, mode = "undirected", diag = FALSE)

num_nodes <- igraph::vcount(gtruth)
num_edges <- igraph::ecount(gtruth)

set.seed(1234)

p1 <- ggraph::ggraph(gtruth, layout = "fr") + 
  ggraph::geom_edge_link(color = "gray", width = 0.5) +  # Set edge color and width
  ggraph::geom_node_point(color = "steelblue", size = 0.7) +  # Set node color and size
  labs(title = paste("Ground Truth\nNodes:", igraph::vcount(gtruth), "Edges:", igraph::ecount(gtruth))) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )

p1

ggsave("./../analysis/simulation/plot/gtruth_top1200_p500.png", p1, width = 8, height = 6, dpi = 300, bg = "white")
```

## Simulate n100 p677 matrices

```{r}
library(distributions3)
nodes <- nrow(adjm)
simat <- zinb_simdata(
  n = 100, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c((3*nodes)-500, (3*nodes)+500)
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n100p500.RDS")

simat <- zinb_simdata(
  n = 100, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10), c(1, 12), c(1,15)),
  mu_noise = c(1, 3, 5, 7, 9),  
  theta = c(1, 0.7, 0.5, 0.3, 0.2),  
  pi = c(0.2, 0.2, 0.2, 0.2, 0.2),  
  kmat = 5,
  depth_range = c((3*nodes)-500, (3*nodes)+500)
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n100p500k5.RDS")

simat <- zinb_simdata(
  n = 500, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c((3*nodes)-500, (3*nodes)+500)
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n500p500.RDS")




```

## Adjacency matrix top500

```{r Generate Adjacency matrice}

pathgenes <- selgene(seurat_object = seurat_subset_filt, cell_type = "CD4-positive helper T cell", top_n = 500)

options(timeout = 2000)
result <- stringdb_adjacency(
  genes          = pathgenes,
  species        = 9606,
  required_score = 900,
  keep_all_genes = F
)

wadjm <- result$weighted
adjm <- result$binary

common_names <- intersect(rownames(adjm), colnames(adjm))
adjm <- adjm[common_names, common_names, drop = FALSE]

sorted_names <- sort(rownames(adjm))
adjm <- adjm[sorted_names, sorted_names]

write.table(adjm, "./../analysis/simulation/adjacency/adjm_top500_p200.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)
write.table(wadjm, "./../analysis/simulation/adjacency/wadjm_top500_p200.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)

```


## Create Ground Truth Network

```{r plot Ground truth}
gtruth <- igraph::graph_from_adjacency_matrix(adjm, mode = "undirected", diag = FALSE)

num_nodes <- igraph::vcount(gtruth)
num_edges <- igraph::ecount(gtruth)

set.seed(1234)

p1 <- ggraph::ggraph(gtruth, layout = "fr") + 
  ggraph::geom_edge_link(color = "gray", width = 0.5) +  # Set edge color and width
  ggraph::geom_node_point(color = "steelblue", size = 0.7) +  # Set node color and size
  labs(title = paste("Ground Truth\nNodes:", igraph::vcount(gtruth), "Edges:", igraph::ecount(gtruth))) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )

p1

ggsave("./../analysis/simulation/plot/gtruth_top500_p200.png", p1, width = 8, height = 6, dpi = 300, bg = "white")
```

## Simulate n100 p271 matrices


```{r}
nodes <- nrow(adjm)
b      <- 3
sigma  <- 0.2

simat <- zinb_simdata(
  n = 100, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c(round((1-sigma)*nodes*b), round((1+sigma)*nodes*b))
)

  depth_range <- c(p, p * sqrt(n))
saveRDS(simat, "./../analysis/simulation/simdata/sim_n100p200.RDS")

simat <- zinb_simdata(
  n = 500, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c(round((1-sigma)*nodes*b), round((1+sigma)*nodes*b))
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n500p200.RDS")

```


## Adjacency matrix top200

```{r Generate Adjacency matrice}

pathgenes <- selgene(seurat_object = seurat_subset_filt, cell_type = "CD4-positive helper T cell", top_n = 200)

options(timeout = 2000)
result <- stringdb_adjacency(
  genes          = pathgenes,
  species        = 9606,
  required_score = 900,
  keep_all_genes = F
)

wadjm <- result$weighted
adjm <- result$binary

common_names <- intersect(rownames(adjm), colnames(adjm))
adjm <- adjm[common_names, common_names, drop = FALSE]

sorted_names <- sort(rownames(adjm))
adjm <- adjm[sorted_names, sorted_names]

write.table(adjm, "./../analysis/simulation/adjacency/adjm_top200_p100.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)
write.table(wadjm, "./../analysis/simulation/adjacency/wadjm_top200_p100.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)

```


## Create Ground Truth Network

```{r plot Ground truth}
gtruth <- igraph::graph_from_adjacency_matrix(adjm, mode = "undirected", diag = FALSE)

num_nodes <- igraph::vcount(gtruth)
num_edges <- igraph::ecount(gtruth)

set.seed(1234)

p1 <- ggraph::ggraph(gtruth, layout = "fr") + 
  ggraph::geom_edge_link(color = "gray", width = 0.5) +  # Set edge color and width
  ggraph::geom_node_point(color = "steelblue", size = 0.7) +  # Set node color and size
  labs(title = paste("Ground Truth\nNodes:", igraph::vcount(gtruth), "Edges:", igraph::ecount(gtruth))) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )

p1

ggsave("./../analysis/simulation/plot/gtruth_top200_p100.png", p1, width = 8, height = 6, dpi = 300, bg = "white")

```

## Simulate n200 p82 matrices


```{r}
nodes <- nrow(adjm)

simat <- zinb_simdata(
  n = 100, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c(round((1-sigma)*nodes*b), round((1+sigma)*nodes*b))
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n100p100.RDS")

simat <- zinb_simdata(
  n = 500, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c(round((1-sigma)*nodes*b), round((1+sigma)*nodes*b))
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n500p100.RDS")

```


```{r Generate Adjacency matrice}

pathgenes <- selgene(seurat_object = seurat_subset_filt, cell_type = "CD4-positive helper T cell", top_n = 1600)

options(timeout = 2000)
result <- stringdb_adjacency(
  genes          = pathgenes,
  species        = 9606,
  required_score = 900,
  keep_all_genes = F
)

wadjm <- result$weighted
adjm <- result$binary

common_names <- intersect(rownames(adjm), colnames(adjm))
adjm <- adjm[common_names, common_names, drop = FALSE]

sorted_names <- sort(rownames(adjm))
adjm <- adjm[sorted_names, sorted_names]

write.table(adjm, "./../analysis/simulation/adjacency/adjm_top1600_p700.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)
write.table(wadjm, "./../analysis/simulation/adjacency/wadjm_top1600_p700.txt", sep = "\t", quote = FALSE, col.names = TRUE, row.names = TRUE)

```


## Create Ground Truth Network

```{r plot Ground truth}
gtruth <- igraph::graph_from_adjacency_matrix(adjm, mode = "undirected", diag = FALSE)

num_nodes <- igraph::vcount(gtruth)
num_edges <- igraph::ecount(gtruth)

set.seed(1234)

p1 <- ggraph::ggraph(gtruth, layout = "fr") + 
  ggraph::geom_edge_link(color = "gray", width = 0.5) +  # Set edge color and width
  ggraph::geom_node_point(color = "steelblue", size = 0.7) +  # Set node color and size
  labs(title = paste("Ground Truth\nNodes:", igraph::vcount(gtruth), "Edges:", igraph::ecount(gtruth))) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )

p1

ggsave("./../analysis/simulation/plot/gtruth_top1600_p700.png", p1, width = 8, height = 6, dpi = 300, bg = "white")

```

## Simulate n200 p82 matrices


```{r}
nodes <- nrow(adjm)

simat <- zinb_simdata(
  n = 100, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c(round((1-sigma)*nodes*b), round((1+sigma)*nodes*b))
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n100p700.RDS")

simat <- zinb_simdata(
  n = 500, 
  p = nodes, 
  B = adjm, 
  mu_range = list(c(1, 4), c(1, 7), c(1, 10)),
  mu_noise = c(1, 3, 5),  
  theta = c(1, 0.7, 0.5),  
  pi = c(0.2, 0.2, 0.2),  
  kmat = 3,
  depth_range = c(round((1-sigma)*nodes*b), round((1+sigma)*nodes*b))
)

saveRDS(simat, "./../analysis/simulation/simdata/sim_n500p700.RDS")

```

